### ISSUE TITLE
Restrict Item Use

### ISSUE THREAD

**Issue by Fyrsta** [TranxCraft/iTranxCraft#10]
This needs similar functionality to the previous plugin but instead should load the information from the database instead.

**Comment by Wild1145** [comment]
@WickedGamingUK Is this like a "Item Blocker" to stop players using certain items or am I misunderstanding the point of this?

**Comment by Fyrsta** [comment]
@Wild1145 This is meant to stop players using items they're not allowed to. For example regular players being blocked from using lava.

**Comment by Wild1145** [comment]
@WickedGamingUK Why should they not be able to use blocks like lava, especially in the survival server parts of the server?

**Comment by Fyrsta** [comment]
@Wild1145 Well it can be used for griefing and other malicious uses. When a player has been around for long enough (few weeks, probably) and we know won't cause trouble they'll be given access to these other blocks. This is a feature that I originally saw on a different survival server and it works well.

**Comment by Wild1145** [comment]
@WickedGamingUK Ahh, Okay. I like that. I thought it was just a straight out block of the items, but that does sound quite handy and like it would work well.
