### ISSUE TITLE
Warn system

### ISSUE THREAD

**Issue by Fyrsta** [TranxCraft/iTranxCraft#15]
One of the core features listed. It needs functionality similar to the previous plugin.

**Comment by Wild1145** [comment]
Something like the DarthCraftMod warning system would probably be perfect for what you are trying to get here. https://github.com/DarthCraft/DarthCraft/blob/master/src/net/darthcraft/dcmod/addons/WarningSystem.java

**Comment by Fyrsta** [comment]
@Wild1145 That's a different type of warning system. This is designed for when the offense is not bannable but the player should be aware to avoid being banned later on.

**Comment by Wild1145** [comment]
@WickedGamingUK Fair enough, however if you are just looking to kick and such you could modify the sanctions, or is this more of a "Fuck up again, then your banned" system where one warning is about all you get?

**Comment by Fyrsta** [comment]
@Wild1145 That sounds like quite a good idea, actually. I'll integrate that when I get round to implementing this feature.
