### ISSUE TITLE
Personal Warp System

### ISSUE THREAD

**Issue by Fyrsta** [TranxCraft/iTranxCraft#19]
A feature to allow players to create their own set of warps that others cannot access. This will be handy as the player could set up warp points such as home, their mine, etc.

**Comment by Wild1145** [comment]
So the essentials /home then?

**Comment by Fyrsta** [comment]
@Wild1145 Not exactly, this will be like /warp. Perhaps /pwarp for personal warp.

**Comment by Wild1145** [comment]
@WickedGamingUK What I mean is, will it be doing the same as /home with essentials where you set your "home" or in this case, personal warp, then you can use it to get you there??

**Comment by Fyrsta** [comment]
@Wild1145 In terms of command features it will be very similar to /warp. You'll have /pwarp to warp to whatever location and /setpwarp to define a new warp.

Command examples:
/pwarp home
/setpwarp mine

**Comment by Wild1145** [comment]
@WickedGamingUK Yeah, its nearly identical to home, just instead of /pwarp its /home with essentials. So its /sethome <name> then just /home <name>

**Comment by Fyrsta** [comment]
@Wild1145 Yeah but with that it just seems to be to do with homes only due to the name. It's essentially the same idea, though.

**Comment by mgejay** [comment]
I like the idea, but just redirect sethome if you dont want any trouble. :P

**Comment by Fyrsta** [comment]
@TheRevalation What do you mean by that?

**Comment by mgejay** [comment]
@WickedGamingUK As wild said, it would be the same as /home, so you can just create a command that when ran, runs another command, like my plugin, /promote runs  /manuadd user group. And broadcasts a promote msg, so do that to easy your life

**Comment by Fyrsta** [comment]
@TheRevalation Nah, dispatching commands like that isn't a good idea. Also, this isn't exactly meant for a player's home.

**Comment by mgejay** [comment]
@WickedGamingUK So, you are looking to make a new private system of warps?

**Comment by Fyrsta** [comment]
@TheRevalation Basically, yeah. Players can set warp points to anywhere they want.
