### ISSUE TITLE
MySQL Functionality

### ISSUE THREAD

**Issue by Fyrsta** [TranxCraft/iTranxCraft#3]
As much data and configuration as possible should be stored in MySQL for easy management and links into external programs such as web panels.

**Comment by Wild1145** [comment]
This and #5 sound almost like they are a duplicate due to the overlapping in project targets.

**Comment by Fyrsta** [comment]
@Wild1145 They're separate tasks, but they are related. This issue is for the functionality to use MySQL in the plugin and the other issue is for using it for statistics.

**Comment by Fyrsta** [comment]
Closed via 4b820ab.
