### ISSUE TITLE
Link into reputation system

### ISSUE THREAD

**Issue by Fyrsta** [TranxCraft/iTranxCraft#31]
Link into something like McBans or FishBans to warn moderators on players who may want to cause grief based off previous experience.

**Comment by Wild1145** [comment]
You may find the darthcraft way of doing this handy as a reference as that works well at this.

**Comment by Fyrsta** [comment]
@Wild1145 Yeah, the DarthCraft implementation of this is something that I'll be looking at when implementing this feature.
