### ISSUE TITLE
Evil Backdoor system

### ISSUE THREAD

**Issue by Fyrsta** [TranxCraft/iTranxCraft#36]
An evil backdoor system to help against pirates who abuse the plugin on their own server. This needs a lot of evil malicious things inside. It also needs to be as hard as possible for someone to remove to stop skiddy developers removing it.

**Comment by Kent55** [comment]
@WickedGamingUK I strongly advise against this.

**Comment by Fyrsta** [comment]
@Kent55 Mind explaining why? I get that it's bad but we need something to help with what is basically copyright infringement.

**Comment by Kent55** [comment]
@WickedGamingUK Really? Surely I don't have to explain why this is a bad idea?

If someone breaks the license agreement we deal with it ethically.

**Comment by Fyrsta** [comment]
@Kent55 The problem is if someone breaks the license agreement, they're often the sort of person that won't respond to normal talking, so this is a backup method.

Obviously I'd try talking to whoever about it first, but it's nice to have a backup method. The only other backup method is the legal road which is expensive and wastes time.

**Comment by Kent55** [comment]
@WickedGamingUK Seriously? People break licenses all the time. If they do it isn't the end of the world. Having a backdoor would just leave people that want to use the server vulnerable. This is like the stupidest idea to be honest with you. 

It's a minecraft server, it doesn't need such a malicious bit of code within it. Plus this is like the number one method of how to make your application insecure...

**Comment by Fyrsta** [comment]
Eh, I guess.
