### ISSUE TITLE
Add url?

### ISSUE THREAD

**Issue by mgejay** [TranxCraft/iTranxCraft#46]
If we have ban appeals, add it to the kick player/kick player on join message in /ban

**Comment by mgejay** [comment]
Add the forum url*

**Comment by mgejay** [comment]
@wickedgaminguk

**Comment by Fyrsta** [comment]
Nah, I don't think this is worthwhile. Since players are forced to join on play.tranxcraft.com, if they get banned, they should have the competence to go to tranxcraft.com, where they can find a link to the forums.

If a player can't do that, they probably lack the mentality to submit a ban appeal of good enough quality to warrant an unban.

**Comment by Wild1145** [comment]
I actually think this should be added. You also should remember that other servers may well use this plugin, and that you should make it at least somewhat flexible. You may assume people will have the required level of competence to do that, but you also have to think, what if they forget what the IP they joined on was, or what if they just dont want to have to find it to file an appeal. You may well loose a lot of players through this when it could be reasonably easily avoided.

**Comment by Fyrsta** [comment]
@Wild1145 If they don't want to find where to post an appeal, then they obviously don't care about playing on the server, which is true for the majority of griefers and trollers. Players will either join on direct IP or save the server to their list, which you can easily extract the IP out of that unless you join a different server if you joined on direct IP. I don't see players not being able to find the IP they joined on a problem.

Your point on other servers using the plugin though is valid. I should at some point have more extensive SQL checks to see if everything is there as it should be and whatnot. I guess this sort of thing could be useful for other servers.

**Comment by Fyrsta** [comment]
Discuss on #47, now.
