### ISSUE TITLE
Log player time

### ISSUE THREAD

**Issue by Fyrsta** [TranxCraft/iTranxCraft#53]
One thing that was suggested in College today, logging the amount of time a player has played would be a very good thing to log. Having the total amount of time played would be nice as well.

**Comment by Kent55** [comment]
Defo

**Comment by mgejay** [comment]
college, :)

**Comment by Fyrsta** [comment]
Well, @JeromSar has done good work with https://github.com/Pravian/Pendulum, so we'll use that for this.
