### ISSUE TITLE
GeoIP Usage

### ISSUE THREAD

**Issue by Fyrsta** [TranxCraft/iTranxCraft#57]
A way to determine where the player is from based off of their IP address. Using the Maxmind Database system would be the best way of implementing this feature,

**Comment by Kent55** [comment]
So are we going to have like the fucking flag of their country and shit? @WickedGamingUK

**Comment by WickedGamingUK** [comment]
@Kent55 No, currently it'll just say where they're from when they login.

**Comment by Kent55** [comment]
Great, yeah, fucking brill fam. Do it innit, get some fucking booze in there too!

Great deals here: http://www.bargainbooze.co.uk
